repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, "--extend-ignore=E203,E741"]
  - repo: https://github.com/glotzerlab/pre-commit-clang-format
    rev: v1.1.0
    hooks:
    - id: clang-format
