name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install doc dependencies
        run: |
          sudo apt update --yes && sudo apt install --yes git
          uv pip install --system . -U pip towncrier
          uv pip install --system . --group dev -e .
          git describe --tags

      - name: Produce Changelog
        run: |
          towncrier build --yes --version==0.0.0
