name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

env:
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes
  GITHUB_PR_NUMBER: ${{ github.event.number }}

jobs:
  mamba:
    runs-on: ubuntu-latest
    defaults:
      run:
        # We need login shells (-l) for micromamba to work.
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install doc dependencies
        run: |
          sudo apt update --yes && sudo apt install --yes git 
          pip install -U pip towncrier

      - name: Produce Changelog
        run: |
          towncrier build --yes --version==0.0.0
